using IotDb.MeasurementManagement.EntityFrameworkCore;
using Xunit;

namespace IotDb.MeasurementManagement.EntityFrameworkCore;

public class MeasurementManagementEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<MeasurementManagementEntityFrameworkCoreFixture>
{

}
